services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ggames
  redis:
    image: redis:7.4.5-alpine
    ports:
      - "6379:6379"